# Generated by Django 5.0.1 on 2024-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dec', models.CharField(max_length=16, verbose_name='Numéro de décision')),
                ('solution', models.CharField(max_length=16, verbose_name='Solution')),
                ('article38', models.CharField(blank=True, max_length=8, null=True, verbose_name='Donnée CRJ')),
                ('date_dec', models.CharField(max_length=8, verbose_name='Date de décision')),
                ('annee_election', models.IntegerField(verbose_name="Année d'élection")),
                ('nom_dep', models.CharField(max_length=16, verbose_name='Nom du département')),
                ('circonscription', models.SmallIntegerField(verbose_name='Numéro de circonscription')),
                ('tf_nb_exprimees', models.IntegerField(verbose_name='Nb voix exprimées tour final')),
                ('tf_nb_votant', models.IntegerField(verbose_name='Nb voix votant tour final')),
                ('tf_nb_inscrit', models.IntegerField(verbose_name='Nb voix inscrits tour final')),
                ('tf_ecart1', models.IntegerField(verbose_name='Tour final, écart candidat 1 et 2')),
            ],
        ),
    ]
