# Generated by Django 5.0.1 on 2024-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisions',
            name='date_dec',
            field=models.CharField(max_length=16, verbose_name='Date de décision'),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='solution',
            field=models.CharField(max_length=32, verbose_name='Solution'),
        ),
    ]
