# Generated by Django 5.0.1 on 2024-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_decisions_date_dec_alter_decisions_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisions',
            name='id',
        ),
        migrations.AlterField(
            model_name='decisions',
            name='numero_dec',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Numéro de décision'),
        ),
    ]
