# Generated by Django 5.0.1 on 2024-01-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_decisions_id_alter_decisions_numero_dec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=64, null=True, verbose_name='Lien de décision')),
                ('numero_dec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.decisions', verbose_name='Numéro de décision')),
            ],
        ),
    ]
