# Generated by Django 5.0.1 on 2024-01-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='numero_dec',
            new_name='numero',
        ),
    ]
