# Generated by Django 5.0.1 on 2024-01-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_links_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.decisions', verbose_name='Numéro de décision'),
        ),
    ]
